### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by sbormann** [simatec/ioBroker.tinker#10]
Hi,
thank you for the gread adapter. Works like a charm.
Two suggrestions:
* is it possible to add units to the datapoints? Like °C or Mb?
* And i think the datapoints should be readonly (common.write=false).

Again, thank you!

**Comment by simatec** [comment]
Hi Sebastian, 
sorry für die späte Antwort... hatte kaum Zeit für die Projekte. 
Ich nehme das mal mit auf meiner Todo auf. 

PS: Klasse Adapter dein Iqontrol 👌
