### ISSUE TITLE
Kann cpu_frequency nicht finden

### ISSUE THREAD

**Issue by emddummi** [simatec/ioBroker.tinker#2]
Adapter läuft auf tinkerboard s als Host, zeigt alles an ausser frequency, die findet er nicht...

**Comment by simatec** [comment]
Steht schon auf meiner Todo und wird die nächsten Tage angepasst

**Comment by asgothian** [comment]
Ich hab mir das ganze im Detail angeschaut, und eine zumindest mögliche Lösung gefunden:

An Statt 
`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq` 
als Befehl zu nutzen habe ich
`test -r /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_frew && cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq || cat /sys/devices/system/cpu/cpufreq/policy0/scaling_cur_freq`
eingetragen.

Was ich nicht gefunden habe ist an welcher Stelle der Befehl im Adapter hinterlegt ist. Ich habe direkt das entsprechende Objekt gepatched und bei mir läuft es.

A.

**Comment by simatec** [comment]
Fix in v1.3.0
