### ISSUE TITLE
Adapter has persistent entries in the log file due to wrong data type

### ISSUE THREAD

**Issue by HJS72** [simatec/ioBroker.tinker#64]
Datapoint is type number but Adapter sends string.

Example Lofile:
`tinker.0 | 2022-08-03 20:27:24.634 | info | State value to set for "tinker.0.cpu.load1" has to be type "number" but received type "string"
tinker.0 | 2022-08-03 20:26:24.625 | info | State value to set for "tinker.0.cpu.load15" has to be type "number" but received type "string"
tinker.0 | 2022-08-03 20:26:24.624 | info | State value to set for "tinker.0.cpu.load5" has to be type "number" but received type "string"`

**Comment by simatec** [comment]
fix in v1.3.0
