### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [simatec/ioBroker.tinker#90]
❗ [E150] No common.connectionType found in [io-package.json](https://github.com/simatec/ioBroker.tinker/blob/master/io-package.json)
 ❗ [E152] No common.dataSource found in [io-package.json](https://github.com/simatec/ioBroker.tinker/blob/master/io-package.json)
 👀 [W171] "common.title" is deprecated in [io-package.json](https://github.com/simatec/ioBroker.tinker/blob/master/io-package.json)
 👀 [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
 👀 [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
 👀 [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/simatec/ioBroker.tinker/blob/master/io-package.json)
 use a React based UI

**Comment by simatec** [comment]
done...
